APLA/Models/EducationStream.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace APLA.Models
{
    [Table("Apla_EducationStream")]
    public class EducationStream
    {
        public EducationStream()
        {
            this.Subjects = new HashSet<Subject>();
            this.Teachers = new HashSet<Teacher>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }

    }
}

APLA/Controllers/EducationStreamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APLA.Models;
using APLA.DAL;

namespace APLA.Controllers
{
    public class EducationStreamController : Controller
    {
        private AplaEntities db = new AplaEntities();

        //
        // GET: /EducationStream/

        public ActionResult Index()
        {
            return View(db.EducationStreams.ToList());
        }

        //
        // GET: /EducationStream/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    EducationStream educationstream = db.EducationStreams.Find(id);
        //    if (educationstream == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(educationstream);
        //}

        //
        // GET: /EducationStream/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /EducationStream/Create

        [HttpPost]
        public ActionResult Create(EducationStream educationstream)
        {
            if (ModelState.IsValid)
            {
                db.EducationStreams.Add(educationstream);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(educationstream);
        }

        //
        // GET: /EducationStream/Edit/5

        public ActionResult Edit(int id = 0)
        {
            EducationStream educationstream = db.EducationStreams.Find(id);
            if (educationstream == null)
            {
                return HttpNotFound();
            }
            return View(educationstream);
        }

        //
        // POST: /EducationStream/Edit/5

        [HttpPost]
        public ActionResult Edit(EducationStream educationstream)
        {
            if (ModelState.IsValid)
            {
                db.Entry(educationstream).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(educationstream);
        }

        //
        // GET: /EducationStream/Delete/5

        public ActionResult Delete(int id = 0)
        {
            EducationStream educationstream = db.EducationStreams.Find(id);
            if (educationstream == null)
            {
                return HttpNotFound();
            }
            return View(educationstream);
        }

        //
        // POST: /EducationStream/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            EducationStream educationstream = db.EducationStreams.Find(id);
            db.EducationStreams.Remove(educationstream);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

APLA/Controllers/PublicTeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APLA.Models;
using APLA.DAL;
using WebMatrix.WebData;
using System.Web.Security;
using APLA.Common;
using System.Collections;
using APLA.Helpers;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using PagedList;
using System.Web.Configuration;
using Elmah;
using System.Net.Mail;
using System.Text;

namespace APLA.Controllers
{
    public class PublicTeacherController : Controller
    {
        private AplaEntities db = new AplaEntities();

        //
        // GET: /PublicTeacher/

        //public ActionResult Index()
        //{
        //    var teachers = db.Teachers.Include(t => t.Race).Include(t => t.Religion);
        //    return View(teachers.ToList());
        //}

        //
        // GET: /PublicTeacher/Details/5
        [Authorize(Roles = "Internal")]
        public ActionResult Details(int id = 0)
        {
            try
            {
                if (id == 0)
                {
                    id = WebSecurity.GetUserId(User.Identity.Name);
                }

                Teacher teacher = db.Teachers.Where(t => t.UserId == id).SingleOrDefault();

                if (teacher == null)
                {
                    return RedirectToAction("Create");
                }

                var currentDistrictResult = db.Districts.Where(d => d.Id == teacher.CurrentDistrictId).FirstOrDefault();
                string currentDistrict = string.Empty;
                if (currentDistrictResult != null)
                {
                    currentDistrict = currentDistrictResult.DistrictName;
                }

                var currentCityResult = db.City.Where(d => d.Id == teacher.CurrentCityId).FirstOrDefault();
                string currentCity = string.Empty;
                if (currentCityResult != null)
                {
                    currentCity = currentCityResult.CityName;
                }

                var permanentDistrictResult = db.Districts.Where(d => d.Id == teacher.PermanentDistrictId).FirstOrDefault();
                string permanentDistrict = string.Empty;
                if (permanentDistrictResult != null)
                {
                    permanentDistrict = permanentDistrictResult.DistrictName;
                }

                var permanentCityResult = db.City.Where(d => d.Id == teacher.PermanentCityId).FirstOrDefault();
                string permanentCity = string.Empty;
                if (permanentCityResult != null)
                {
                    permanentCity = permanentCityResult.CityName;
                }

                ViewBag.CurrentAddress = string.Format("{0},{1},{2}", teacher.CurrentLane, currentCity, currentDistrict);
                ViewBag.permanentAddress = string.Format("{0},{1},{2}", teacher.PermanentLane, permanentCity, permanentDistrict);
                ViewBag.Name = string.Format("{0} {1} {2}", teacher.Name, teacher.CommonName, teacher.FullName);

                return View(teacher);
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                WebSecurity.Logout();
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult TeacherDetails(int id = 0,int page=0)
        {
            try
            {
                ViewBag.Page = page;
                Teacher teacher = db.Teachers.Where(t => t.Id == id).SingleOrDefault();

                if (teacher == null)
                {
                    return RedirectToAction("Index", "Home", null);
                }

                var currentDistrictResult = db.Districts.Where(d => d.Id == teacher.CurrentDistrictId).FirstOrDefault();
                string currentDistrict = string.Empty;
                if (currentDistrictResult != null)
                {
                    currentDistrict = currentDistrictResult.DistrictName;
                }

                var currentCityResult = db.City.Where(d => d.Id == teacher.CurrentCityId).FirstOrDefault();
                string currentCity = string.Empty;
                if (currentCityResult != null)
                {
                    currentCity = currentCityResult.CityName;
                }

                var permanentDistrictResult = db.Districts.Where(d => d.Id == teacher.PermanentDistrictId).FirstOrDefault();
                string permanentDistrict = string.Empty;
                if (permanentDistrictResult != null)
                {
                    permanentDistrict = permanentDistrictResult.DistrictName;
                }

                var permanentCityResult = db.City.Where(d => d.Id == teacher.PermanentCityId).FirstOrDefault();
                string permanentCity = string.Empty;
                if (permanentCityResult != null)
                {
                    permanentCity = permanentCityResult.CityName;
                }

                ViewBag.CurrentAddress = string.Format("{0},{1},{2}", teacher.CurrentLane, currentCity, currentDistrict);
                ViewBag.permanentAddress = string.Format("{0},{1},{2}", teacher.PermanentLane, permanentCity, permanentDistrict);
                ViewBag.Name = string.Format("{0} {1} {2}", teacher.Name, teacher.CommonName, teacher.FullName);

                ViewBag.TimeTables = db.TimeTables.Where(t => t.TeacherId == id).ToList();

                return View(teacher);
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /PublicTeacher/Create
        [Authorize(Roles = "SuperAdmin,Admin")]
        public ActionResult Create()
        {
            try
            {
                string fmt = "00000.##";
                string NewReg = string.Empty;
                string reg = string.Empty;
                int maxRegNo = 0;
                List<int> numbers = new List<int>();
                int newRegNo = 0;

                var teacherList = db.Teachers;
                if (teacherList != null && teacherList.Count() > 0)
                {
                    foreach (Teacher t in teacherList.ToList())
                    {
                        reg = t.RegNo;
                        int regNo = 0;
                        if (!string.IsNullOrEmpty(reg))
                        {
                            var array = reg.Split('_');
                            regNo = Convert.ToInt32(array[2]);
                            numbers.Add(regNo);
                        }
                    }

                    var max = db.Teachers.OrderByDescending(t => t.RegNo).FirstOrDefault();
                    if (max != null)
                    {
                        var array = max.RegNo.Split('_');
                        maxRegNo = Convert.ToInt32(array[2]);
                    }

                    var result = Enumerable.Range(1, maxRegNo).Except(numbers);
                    if (result != null && result.Count() > 0)
                    {
                        newRegNo = result.FirstOrDefault();
                    }
                    else
                    {
                        newRegNo = maxRegNo + 1;
                    }
                }
                else
                {
                    newRegNo = 1;
                }

                NewReg = string.Format("Apla_{0}_{1}", DateTime.Now.Year, newRegNo.ToString(fmt));

                ViewBag.CityId = new SelectList(db.City, "Id", "CityName");
                ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
                ViewBag.RaceId = new SelectList(db.Races, "Id", "Name");
                ViewBag.ReligionId = new SelectList(db.Religions, "Id", "Name");

                ViewBag.EducationStreams = db.EducationStreams.ToList();
                ViewBag.Institutes = db.Institutes.ToList();
                ViewBag.Occupations = db.Occupations.ToList();
                ViewBag.Reg = NewReg;
                ViewBag.Names = new SelectList((IEnumerable)SelectListItemHelper.GetPersonDetails(), "Text", "Value");
                return View();
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /PublicTeacher/Create

        [HttpPost]
        [Authorize(Roles = "SuperAdmin,Admin")]
        public ActionResult Create(Teacher teacher, HttpPostedFileBase file)
        {
            try
            {
                bool validationResult = false;
                var keys = Request.Form.AllKeys.ToList();

                foreach (var key in keys)
                {
                    if (key.ToString().StartsWith("s"))
                    {
                        validationResult = true;
                    }
                }

                int iFileSize = 0;

                if (file != null)
                {
                    iFileSize = file.ContentLength;
                }

                if (iFileSize > 5000000)  // 1MB approx (actually less though)
                {
                    // File is too big so do something here
                    ViewBag.Error = "File exceeds the maximum file size 5MB";
                }

                string userName = string.Empty;

                try
                {

                    if (ModelState.IsValid && validationResult && iFileSize < 5000000)
                    {
                        userName = Request["username"];
                        var password = Request["password"];
                        WebSecurity.CreateUserAndAccount(userName, password);
                        var roles = (SimpleRoleProvider)Roles.Provider;

APLA/Views/PublicTeacher/EducationStream.cshtml
@model APLA.Models.EducationStream

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EducationStream</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

APLA/Views/PublicTeacher/Events.cshtml
@{
    ViewBag.Title = "Events";
}

<style>
        .img12{
    width:100%;
    height: 100%;
}
</style>

<div class="container">
    <div>
    <a href="~/guru_geethaya.mp3" target="_blank">Download Theme Song</a>
        </div>
    <hr class="featurette-divider">
    <div>
        <a href="~/diri_sawiya_application.pdf" target="_blank">Download Donation Application</a>
    </div>
    <hr class="featurette-divider">
    <img class="img12" src="~/Content/images/Events1.PNG" />
    <br/>
    <hr class="featurette-divider">
    <img class="img12" src="~/Content/images/Events2.PNG" />
    </div>

APLA/Views/PublicTeacher/SeachTeacher.cshtml
@*@model PagedList.IPagedList<APLA.Models.Teacher>*@
@model IEnumerable<APLA.Models.Teacher>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@*<div class="container">
    <div class="row">
        <legend>Teacher List</legend>

        @using (Html.BeginForm("SeachTeacher", "PublicTeacher", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="input-group">
               Find by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder="Search"})
                 <span class="">
                            <input class="btn btn-default" type="submit" value="Search" />
                 </span>
            </div>   
        }

     <table class="table table-bordered table-striped">
					<tr>
						<th style="text-align: center">Profile Image</th>
						<th style="text-align: center">Reg No</th>
						<th style="text-align: center">Name</th>
						<th style="text-align: center">View Profile</th>
					</tr>
    
@foreach (var item in Model)
{
    <tr>
        <td>
          @{
            var imgPath = Directory.EnumerateFiles(Server.MapPath(@"~/Images/ProfileImages/"), "*.*", SearchOption.AllDirectories).Where(s => s.Contains(item.RegNo));
                if(imgPath!=null && imgPath.Count()>0){

                            var img = new FileInfo(imgPath.First());
                            if(img!=null){
                                <img src="@Url.Content(String.Format("~/Images/ProfileImages/{0}",img.Name))" width="50" height="50" />
                            }

                 }
           }

            </td>

    <td>
        
       <div class="controls"> @Html.Label(item.RegNo) 
           </div>
    </td>

     <td>
        
    
        <div class="controls">@Html.Label(item.Name+" "+item.CommonName+" "+item.FullName)</div>
    </td>
        <td class="col-sm-1">
         <a class="btn btn-warning" @Html.ActionLink("View Details", "TeacherDetails", new {id=item.Id })
            </td>
    
    
        </tr>
    
}
  </table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("SeachTeacher",new {page,currentFilter = ViewBag.CurrentFilter}))
</div>
</div>*@

@using GridMvc.Html

<div class="container">
    <div class="row">
@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.RegNo).Titled("Reg No").SetWidth(200).Sortable(true).Filterable(true);
              columns.Add(t => t.CommonName).Titled("First Name").SetWidth(200).Sortable(true).Filterable(true);
              columns.Add(t => t.FullName).Titled("Last Name").SetWidth(200).Sortable(true).Filterable(true);
              columns.Add(t => t.Subjects.First().Name).Titled("Subject").SetWidth(200).Sortable(true).Filterable(true);
              columns.Add().Titled("Options").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View Details", "TeacherDetails", "PublicTeacher", new { id = o.Id, page = ViewBag.Page }, new { @class="btn btn-info"}).ToHtmlString());
          }).WithPaging(10)


    </div>

</div>

APLA/Views/PublicTeacher/TeacherDetails.cshtml
@model APLA.Models.Teacher

@{
    ViewBag.Title = "TeacherDetails";
}

<style>
    .form-horizontal .controls {
    margin-left: 180px;
    margin-top: 5px;
}
    .profile_form {/*
        margin-left:auto;
        margin-right:auto;
        width:50%;*/
    }
   
    .profile_img 
    {
        	background-position: right;
            margin-bottom:30px; width:100px;
        height:100px;
    }
    .profile_details
    {
        margin-top:5px;
    }
    .control-label {
        font-weight:bold;
    }
     .timetable_div {
        padding-top:20px;
        background-color:#F5F5F5;
    }
    
</style>
<div class="container">
<div class="row">
    <h3 style="color:#005CFE;text-align:center">Teacher Details</h3> <br />
    <legend>Search Teacher</legend>
     <div class="col-xs-2">
       <div class="profile_img">

        @{
                var imgPath = Directory.EnumerateFiles(Server.MapPath(@"~/Images/ProfileImages/"), "*.*", SearchOption.AllDirectories).Where(s => s.Contains(Model.RegNo));
                if(imgPath!=null && imgPath.Count()>0){

                            var img = new FileInfo(imgPath.First());
                            if(img!=null){
                                <img src="@Url.Content(String.Format("~/Images/ProfileImages/{0}",img.Name))" width="100" height="100" />
                            }

                 }
        }
        </div>
    </div>
    <form class="form-horizontal">
    <div class="col-xs-6">
    <div class="form-group">
        <label class="col-sm-4 control-label">Reg No :</label>
       <div class="col-sm-7 profile_details has-success"> 
           @Html.DisplayFor(model => model.RegNo, new { @class="form-control"}) 
           </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">Name :</label>
        <div class="col-sm-7 profile_details">
            @Html.Label((string)ViewBag.Name)
        </div>
        </div>
        
        <div class="form-group">
        <label class="col-sm-4 control-label">Email :</label>
        <div class="col-sm-7 profile_details">
            @Html.DisplayFor(model => model.Email, new { @class="form-control"})
        </div>
        </div> 

        <div class="form-group">
        <label class="col-sm-4 control-label">Mobile Phone :</label>
        <div class="col-sm-7 profile_details">
            @Html.DisplayFor(model => model.Pho_M, new { @class="form-control"})
        </div>
        </div>

         
         
        <div class="form-group">
        <label class="col-sm-4 control-label">Current Address :</label>
        <div class="col-sm-7 profile_details">
            @Html.Label((string)ViewBag.CurrentAddress)
        </div>
        </div> 

        <div class="form-group">
        <label class="col-sm-4 control-label">Permanent Address :</label>
        <div class="col-sm-7 profile_details">
            @Html.Label((string)ViewBag.permanentAddress)
        </div>
        </div>

        <div class="form-group">
        <label class="col-sm-4 control-label">Subjects :</label>
        <div class="col-sm-7 profile_details">
            @foreach (var subject in Model.Subjects){
                <label>@subject.Name</label>
            }
        </div>
        </div>

         <div class="form-group">
        <label class="col-sm-4 control-label">Social Media :</label>
        <div class="col-sm-7 profile_details">
             @if (!string.IsNullOrEmpty(Model.facebook))
                         {
                             <a href="@Model.facebook" target="_blank">
                                 <img src="~/slideshow/fb2.png" width="25" height="25" /></a>
                         }

                         @if (!string.IsNullOrEmpty(Model.twitter))
                         {
                             <a href="@Model.twitter" target="_blank">
                                 <img src="~/slideshow/t2.png" width="25" height="25" /></a>
                         }

                         @if (!string.IsNullOrEmpty(Model.googlePlus))
                         {
                             <a href="@Model.googlePlus" target="_blank">
                                 <img src="~/slideshow/g1.png" width="25" height="25" /></a>
                         }

                         @if (!string.IsNullOrEmpty(Model.linkedIn))
                         {
                             <a href="@Model.linkedIn" target="_blank">
                                 <img src="~/slideshow/linkedin.png" width="25" height="25" /></a>
                                 
                         }
                         @if (!string.IsNullOrEmpty(Model.youTube))
                         {
                             <a href="@Model.youTube" target="_blank">
                                 <img src="~/slideshow/u1.png" width="25" height="25" /></a>
                         }
        
        </div>
        </div>

    </div>
        </form>
</div>
    <div class="col-xs-9">
        @Html.Partial("_TeacherTimeTables",(IEnumerable<APLA.Models.TimeTable>)ViewBag.TimeTables)
    </div>
</div>
    

<div class="container">
 @*   <a class="btn btn-info" @Html.ActionLink("Back", "SeachTeacher", "PublicTeacher",new { grid=ViewBag.Page },null) *@
    <div class="row">
    <a class="btn btn-info" href="/PublicTeacher/SeachTeacher?grid-page=@ViewBag.Page">Back</a> 
        </div>
</div>

APLA/Views/PublicTeacher/_TeacherTimeTables.cshtml
@model IEnumerable<APLA.Models.TimeTable>
<br />
<legend style="text-align: center">Teacher Time Table</legend>
<table class="table table-bordered table-hover table-striped">
    <tr>
        <th style="text-align: center">
            @Html.DisplayNameFor(model => model.year)
        </th>
        <th style="text-align: center">
            @Html.DisplayName("Education Stream")
        </th>
        <th style="text-align: center">
            @Html.DisplayName("Subject")
        </th>
        <th style="text-align: center">
            @Html.DisplayName("Class Type")
        </th>
        <th style="text-align: center">
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th style="text-align: center">
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th style="text-align: center">
            @Html.DisplayNameFor(model => model.Venue)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.year)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EducationStream.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClassType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Venue)
        </td>
    </tr>
}

</table>