APLA/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace APLA.Models
{
    [Table("Apla_Subject")]
    public class Subject
    {
        public Subject()
        {
            this.Teachers = new HashSet<Teacher>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int EducationStreamId { get; set; }

        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual EducationStream EducationStream { get; set; }
    }
}

APLA/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APLA.Models;
using APLA.DAL;
using System.Web.Configuration;
using PagedList;

namespace APLA.Controllers
{
    public class SubjectController : Controller
    {
        private AplaEntities db = new AplaEntities();

        //
        // GET: /Subject/

        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var subjects = from t in db.Subjects
                               select t;

            if (!String.IsNullOrEmpty(searchString))
            {
                subjects = subjects.Where(t => t.Name.ToLower().Contains(searchString.ToLower()));
            }

            var result = WebConfigurationManager.AppSettings["SubjectListPageSize"];
            int pageSize = 5;
            if (!string.IsNullOrEmpty(result))
            {
                pageSize = Convert.ToInt32(result);
            }

            int pageNumber = (page ?? 1);

            return View(subjects.ToList().ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Subject/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Subject subject = db.Subjects.Find(id);
        //    if (subject == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(subject);
        //}

        //
        // GET: /Subject/Create

        public ActionResult Create()
        {
            ViewBag.EducationStreamId = new SelectList(db.EducationStreams, "Id", "Name");
            return View();
        }

        //
        // POST: /Subject/Create

        [HttpPost]
        public ActionResult Create(Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EducationStreamId = new SelectList(db.EducationStreams, "Id", "Name", subject.EducationStreamId);
            return View(subject);
        }

        //
        // GET: /Subject/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            ViewBag.EducationStreamId = new SelectList(db.EducationStreams, "Id", "Name", subject.EducationStreamId);
            return View(subject);
        }

        //
        // POST: /Subject/Edit/5

        [HttpPost]
        public ActionResult Edit(Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EducationStreamId = new SelectList(db.EducationStreams, "Id", "Name", subject.EducationStreamId);
            return View(subject);
        }

        //
        // GET: /Subject/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        //
        // POST: /Subject/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subjects.Find(id);
            db.Subjects.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

APLA/Views/Subject/Create.cshtml
@model APLA.Models.Subject

@{
    ViewBag.Title = "Create Subject";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    select, textarea, input[type="text"], input[type="password"] {
        height:35px;
    }
</style>
<div class="container">
    <div class="row">

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
     <div class="form-horizontal" role="form" id="form">    
        <h3>Create Subject</h3>

        <div class="control-group">
         <label class="control-label">@Html.LabelFor(model => model.Name) </label>
        <div class="controls">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name) </div>
        </div>

        <div class="control-group">
         <label class="control-label">@Html.LabelFor(model => model.EducationStreamId, "EducationStream") </label>
        <div class="controls">
            @Html.DropDownList("EducationStreamId", String.Empty)
            @Html.ValidationMessageFor(model => model.EducationStreamId) </div>
        </div>

         <div class="form-actions">
       <button type="submit" class="btn btn-success" value="Create"> Create</button>
             <a class="btn btn-default" @Html.ActionLink("Back to List", "Index")
             </div>
    </div>
}
</div>
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APLA/Views/Subject/Delete.cshtml
@model APLA.Models.Subject

@{
    ViewBag.Title = "Delete Subject";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
<h2>@ViewBag.Title</h2>

<h4 class="alert alert-error">Are you sure you want to delete this @Html.DisplayFor(model => model.Name)?</h4>
<div class="form-actions">
    @using (Html.BeginForm()) {
     <p style="text-align:center">
        <button type="submit" class="btn btn-danger" value="Delete">Yes</button> &nbsp;&nbsp;&nbsp;&nbsp;
        <a class="btn btn-default" @Html.ActionLink("No", "Index")
    </p>
    }
</div>
        </div></div>

APLA/Views/Subject/Details.cshtml
@model APLA.Models.Subject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Subject</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EducationStream.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EducationStream.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

APLA/Views/Subject/Edit.cshtml
@model APLA.Models.Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>

    select, textarea, input[type="text"]{
        height:35px;
    }
</style>
<div class="container">
          <div class="row">
            <div class="container-fluid">
        <legend>Edit Institute</legend></div>

@using (Html.BeginForm(new { @class = "form-inline" }))
{
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.Id)

       <div class="form-group">
         <label class="col-sm-1 control-label">Institute Name</label>
         <div class="col-sm-3">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
           </div>

         <div class="form-group">
            @Html.LabelFor(model => model.EducationStreamId, "Education Stream",new {@class="col-sm-1 control-label"})
        <div class="col-sm-3">
            @Html.DropDownList("EducationStreamId", String.Empty)
            @Html.ValidationMessageFor(model => model.EducationStreamId)
        </div>
             </div>

        <div class="form-group">
            <div class="col-sm-2">
            <button type="submit" class="btn btn-success" value="Save">Save</button> 
                    <a class="btn btn-default" @Html.ActionLink("Back to List", "Index") 
        </div></div>
}

</div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APLA/Views/Subject/Index.cshtml
@model PagedList.IPagedList<APLA.Models.Subject>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Subject List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@*@{       
   var grid = new WebGrid(source: Model,
                defaultSort: "Name",
                canPage:true,
                rowsPerPage: 20);
}
<style type="text/css">
  .grid { margin: 4px; border-collapse: collapse; width: 50%;  margin-bottom: 20px; }
  .grid th, .grid td { border: 1px solid #C0C0C0; padding: 5px; }
  .head { background-color: #E8E8E8; font-weight: bold; color: #000000; }
   .alt { background-color: #E8E8E8; color: #000; }
    .btn_delete {
        width:40%;
        text-align:center;
    }
</style>
<div class="container">
     <div class="row">
        <div class="container-fluid">
    <h2 style="text-align:center;color:#76BCF8">@ViewBag.Title</h2>
    <p> 
        <a class="btn btn-success"  @Html.ActionLink("Create New", "Create") </a>
</p>
    @grid.GetHtml(
        tableStyle: "grid",
        headerStyle: "head",
        alternatingRowStyle: "alt",
        columns: grid.Columns(
            grid.Column("Name"),
            grid.Column(header:"Education Stream", format:@<text><div>@(item.EducationStream.Name)</div></text>),
            grid.Column(header: "Action", format: (item) => new HtmlString(Html.ActionLink("Edit", "Edit", new { id = item.Id }).ToString())),
            grid.Column(header: "Action",format: (item) => (User.IsInRole("SuperAdmin")) ? new HtmlString(Html.ActionLink("Delete", "Delete", new { id = item.Id } ).ToString()) : Html.Raw(""),style:"btn_delete")
        )
    )
</div></div></div>*@

<style>

    select, textarea, input[type="text"], input[type="password"] {
        height:35px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="container-fluid">
            <h2 style="text-align:center;color:#76BCF8">@ViewBag.Title</h2>
    <p> 
        <a class="btn btn-success"  @Html.ActionLink("Create New", "Create") </a>
    </p>
            </div>


@using (Html.BeginForm("Index", "Subject", FormMethod.Get, new { @class="form-inline"}))
{
    <div class="input-group">
       Find by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder="Search"})
         <span class="">
                    <input class="btn btn-default" type="submit" value="Search" />
                </span>
   </div>   
    
}

<table class="table table-bordered table-hover table-striped">
    <tr>
        <th style="text-align: center">
            Name
        </th>
        <th style="text-align: center">
            Education Stream
        </th>
        <th style="text-align: center">Action</th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
             @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
             @Html.DisplayFor(modelItem => item.EducationStream.Name)
        </td>
        <td>
            <a class="btn btn-default" @Html.ActionLink("Edit", "Edit", new { id=item.Id })
            
            <a class="btn btn-danger" @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",new { page, currentFilter = ViewBag.CurrentFilter }))
</div></div>