APLA/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace APLA.Models
{
    [Table("Apla_Teacher")]
    public class Teacher
    {
        public Teacher()
        {
            this.Children = new HashSet<Children>();
            this.Subjects = new HashSet<Subject>();
            this.Institutes = new HashSet<Institute>();
            this.Occupations = new HashSet<Occupation>();
            this.EducationStreams = new HashSet<EducationStream>();
        }

        public int Id { get; set; }
        public string RegNo { get; set; }
        public string Name { get; set; }
        [Required]
        public string CommonName { get; set; }
        public string FullName { get; set; }
        public int CurrentDistrictId { get; set; }
        public int CurrentCityId { get; set; }
        public string CurrentLane { get; set; }
        public int PermanentDistrictId { get; set; }
        public int PermanentCityId { get; set; }
        public string PermanentLane { get; set; }
        public string Pho_R { get; set; }
        public string Pho_O { get; set; }
        [Required]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Invalid Phone No")]
        public string Pho_M { get; set; }
        public string Email { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Birth Day")]
        public Nullable<DateTime> Bday { get; set; }
        [RegularExpression(@"^\d{9}[V|v|x|X]$",ErrorMessage="Please enter a valid Id Number")]
        [StringLength(10)]
        public string NationalId { get; set; }
        public int RaceId { get; set; }
        public int ReligionId { get; set; }
        [Display(Name = "Is married")]
        public bool IsMarried { get; set; }
        public string PartnerName { get; set; }
        public Nullable<DateTime> PartnerBday { get; set; }
        public bool IsPartnerWorking { get; set; }
        public int UserId { get; set; }
        [UIHint("ActiveDeactive")]
        [Display(Name = "Status")]
        public bool Enabled { get; set; }
        public bool Approved { get; set; }

        [Display(Name = "FaceBook")]
        [Url]
        public string facebook { get; set; }
        [Display(Name = "Google Plus")]
        [Url]
        public string googlePlus { get; set; }
        [Display(Name = "Twitter")]
        [Url]
        public string twitter { get; set; }
        [Display(Name = "Linked In")]
        [Url]
        public string linkedIn { get; set; }
        [Display(Name = "You Tube")]
        [Url]
        public string youTube { get; set; }

        public virtual User User { get; set; }
        public virtual Race Race { get; set; }
        public virtual Religion Religion { get; set; }

        public virtual ICollection<Children> Children { get; set; }
        [Required]
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Institute> Institutes { get; set; }
        public virtual ICollection<Occupation> Occupations { get; set; }
        public virtual ICollection<EducationStream> EducationStreams { get; set; }
    }
}

APLA/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using APLA.Models;
using APLA.DAL;
using WebMatrix.WebData;
using System.Web.Security;
using APLA.Common;
using APLA.Helpers;
using System.Collections;
using System.IO;
using PagedList;
using System.Web.Configuration;
using Elmah;

namespace APLA.Controllers
{
    [Authorize(Roles="SuperAdmin,Admin")]
    public class TeacherController : Controller
    {
        private AplaEntities db = new AplaEntities();

        //
        // GET: /Teacher/

        public ActionResult Index()
        {
            try
            {
                string page = string.Empty;
                var queryString = Request.QueryString.GetValues("grid-page");
                if (queryString != null && queryString.Count() > 0)
                {
                    page = queryString.FirstOrDefault();
                    ViewBag.Page = page;
                }

                var teachers = from t in db.Teachers
                               select t;
                return View(teachers.ToList());
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                WebSecurity.Logout();
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /Teacher/Details/5

        public ActionResult Details(int id = 0,int page=0)
        {
            try
            {
                ViewBag.Page = page;
                Teacher teacher = db.Teachers.Find(id);
                if (teacher == null)
                {
                    return HttpNotFound();
                }

                var currentDistrictResult = db.Districts.Where(d => d.Id == teacher.CurrentDistrictId).FirstOrDefault();
                string currentDistrict = string.Empty;
                if (currentDistrictResult != null)
                {
                    currentDistrict = currentDistrictResult.DistrictName;
                }

                var currentCityResult = db.City.Where(d => d.Id == teacher.CurrentCityId).FirstOrDefault();
                string currentCity = string.Empty;
                if (currentCityResult != null)
                {
                    currentCity = currentCityResult.CityName;
                }

                var permanentDistrictResult = db.Districts.Where(d => d.Id == teacher.PermanentDistrictId).FirstOrDefault();
                string permanentDistrict = string.Empty;
                if (permanentDistrictResult != null)
                {
                    permanentDistrict = permanentDistrictResult.DistrictName;
                }

                var permanentCityResult = db.City.Where(d => d.Id == teacher.PermanentCityId).FirstOrDefault();
                string permanentCity = string.Empty;
                if (permanentCityResult != null)
                {
                    permanentCity = permanentCityResult.CityName;
                }

                ViewBag.CurrentAddress = string.Format("{0},{1},{2}", teacher.CurrentLane, currentCity, currentDistrict);
                ViewBag.permanentAddress = string.Format("{0},{1},{2}", teacher.PermanentLane, permanentCity, permanentDistrict);
                ViewBag.Name = string.Format("{0} {1} {2}", teacher.Name, teacher.CommonName, teacher.FullName);

                ViewBag.UserName = db.Users.Where(u => u.UserId == teacher.UserId).SingleOrDefault().UserName;

                return View(teacher);
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Teacher/Details/5

        public ActionResult IdForm(int id = 0)
        {
            try
            {
                Teacher teacher = db.Teachers.Find(id);
                if (teacher == null)
                {
                    return HttpNotFound();
                }

                var permanentDistrict = db.Districts.Where(d => d.Id == teacher.PermanentDistrictId).FirstOrDefault().DistrictName;
                var permanentCity = db.City.Where(d => d.Id == teacher.PermanentCityId).FirstOrDefault().CityName;
                ViewBag.permanentAddress = string.Format("{0},{1},{2}", teacher.PermanentLane, permanentCity, permanentDistrict);
                ViewBag.Name = string.Format("{0} {1} {2}", teacher.Name, teacher.CommonName, teacher.FullName);

                return View(teacher);
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Teacher/Create

        public ActionResult Create()
        {
            try
            {
                string fmt = "00000.##";
                string NewReg = string.Empty;
                string reg = string.Empty;
                int maxRegNo = 0;
                List<int> numbers = new List<int>();
                int newRegNo = 0;

                var teacherList = db.Teachers;
                if (teacherList != null && teacherList.Count() > 0)
                {
                    foreach (Teacher t in teacherList.ToList())
                    {
                        reg = t.RegNo;
                        int regNo = 0;
                        if (!string.IsNullOrEmpty(reg))
                        {
                            var array = reg.Split('_');
                            regNo = Convert.ToInt32(array[2]);
                            numbers.Add(regNo);
                        }
                    }

                    var max = db.Teachers.OrderByDescending(t => t.RegNo).FirstOrDefault();
                    if (max != null)
                    {
                        var array = max.RegNo.Split('_');
                        maxRegNo = Convert.ToInt32(array[2]);
                    }

                    var result = Enumerable.Range(1, maxRegNo).Except(numbers);
                    if (result != null && result.Count() > 0)
                    {
                        newRegNo = result.FirstOrDefault();
                    }
                    else
                    {
                        newRegNo = maxRegNo + 1;
                    }
                }
                else
                {
                    newRegNo = 1;
                }

                NewReg = string.Format("Apla_{0}_{1}", DateTime.Now.Year, newRegNo.ToString(fmt));

                ViewBag.CityId = new SelectList(db.City, "Id", "CityName");
                ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
                ViewBag.RaceId = new SelectList(db.Races, "Id", "Name");
                ViewBag.ReligionId = new SelectList(db.Religions, "Id", "Name");

                ViewBag.EducationStreams = db.EducationStreams.ToList();
                ViewBag.Institutes = db.Institutes.ToList();
                ViewBag.Occupations = db.Occupations.ToList();
                ViewBag.Reg = NewReg;
                ViewBag.Names = new SelectList((IEnumerable)SelectListItemHelper.GetPersonDetails(), "Text", "Value");
                return View();
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);
                return RedirectToAction("Index");
            }
        }

        //
        // POST: /Teacher/Create

        [HttpPost]
        public ActionResult Create(Teacher teacher, HttpPostedFileBase file)
        {
            try
            {
                bool validationResult = false;
                var keys = Request.Form.AllKeys.ToList();

                foreach (var key in keys)
                {
                    if (key.ToString().StartsWith("s"))
                    {
                        validationResult = true;
                    }
                }

                int iFileSize = 0;

                if (file != null)
                {
                    iFileSize = file.ContentLength;
                }

                if (iFileSize > 5000000)  // 1MB approx (actually less though)
                {
                    // File is too big so do something here
                    ViewBag.Error = "File exceeds the maximum file size 5MB";
                }

                string userName = string.Empty;

                try
                {

                    if (ModelState.IsValid && validationResult && iFileSize < 5000000)
                    {
                        userName = Request["username"];
                        var password = Request["password"];
                        WebSecurity.CreateUserAndAccount(userName, password);
                        var roles = (SimpleRoleProvider)Roles.Provider;
                        if (!roles.RoleExists(Common.UserRoles.Internal.ToString()))
                        {
                            roles.CreateRole(Common.UserRoles.Internal.ToString());
                        }

                        Roles.AddUserToRole(userName, UserRoles.Internal.ToString());

                        int userId = WebSecurity.GetUserId(userName);
                        teacher.UserId = userId;


                        if (file != null)
                        {
                            string pic = System.IO.Path.GetExtension(file.FileName);
                            string path = Server.MapPath("~/Images/ProfileImages/" + teacher.RegNo + pic);
                            file.SaveAs(path);
                        }

                        //adding education streams
                        ICollection<EducationStream> educationStreamList = new HashSet<EducationStream>();
                        var educationStreams = db.EducationStreams.ToList();
                        foreach (EducationStream stream in educationStreams)

APLA/Views/Teacher/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model APLA.Models.LocalPasswordModel
<style>

    .subject_divs {
    }
    .form-group {
   /* margin-bottom: 40px;*/
}
    select, textarea, input[type="text"], input[type="password"] {
        height:35px;
    }
     .timetable_div {
        background-color:#F5F5F5;
         padding-top: 40px;
    }
</style>
<div class="container">
    <div class="row">
        <h2 style="text-align:center;color:#94ea66">@ViewBag.Title</h2> <br />
@using (Html.BeginForm("ChangePassword", "Teacher", new { @class = "form-horizontal timetable_div" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.Hidden("UserName", (String)ViewBag.UserName)
    @Html.Hidden("page", (int)ViewBag.Page)

        <legend>Set Password Form</legend>
         <div class="col-xs-6 col-sm-6 col-md-6 column">
                          <div class="form-group">
                            <label class="col-sm-4 control-label">New Password</label>
                 <div class="col-sm-7">@Html.PasswordFor(m => m.NewPassword, new { @class="form-control"})</div>
                              </div>
             <div class="form-group">
                            <label class="col-sm-4 control-label">Confirm Password</label>
                 <div class="col-sm-7">@Html.PasswordFor(m => m.ConfirmPassword, new { @class="form-control"})</div>
                              </div>

              <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success" value="Set password"> Set Password</button>
@*                        <a class="btn btn-default" href="@Url.Action("Index","Home")">Cancle</a>*@
                        <a href="/Teacher/Index?grid-page=@ViewBag.Page">Cancel</a> 
                    </div>
                 </div>
             </div>   
}
</div></div>

APLA/Views/Teacher/Delete.cshtml
@model APLA.Models.Teacher

@{
    ViewBag.Title = "Delete Teacher";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
<h2>@ViewBag.Title</h2>

<h4 class="alert alert-error">Are you sure you want to delete this Teacher?</h4>
<div class="form-actions">
@using (Html.BeginForm()) {
    @Html.Hidden("page",(int)ViewBag.Page)
    <p style="text-align:center">
        <button type="submit" class="btn btn-danger" value="Delete">Yes</button> &nbsp;&nbsp;&nbsp;&nbsp;
@*        <a class="btn btn-default" @Html.ActionLink("No", "Index",new {page=ViewBag.PageNo })*@
        <a class="btn btn-default" href="/Teacher/Index?grid-page=@ViewBag.Page">No</a> 
    </p>
}
    </div>
        </div></div>

APLA/Views/Teacher/IdForm.cshtml
@model APLA.Models.Teacher

@{
    ViewBag.Title = "IdForm";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .form-horizontal .controls {
    margin-left: 180px;
    margin-top: 5px;
}
    .profile_form {/*
        margin-left:auto;
        margin-right:auto;
        width:50%;*/
    }
    select, textarea, input[type="text"], input[type="password"] {
        height:35px;
    }
    .profile_img 
    {
        	background-position: left;
            margin-bottom:60px;
            width:100px;
            height:100px;

    }
    .profile_details
    {
        margin-top:5px;
    }
    .control-label {
        font-weight:bold;
    }
     .timetable_div {/*
        padding-top:20px;
        background-color:#F5F5F5;*/
    }
</style>
<div class="container">
    <div class="row">
        <div id="Content">

            <h3 style="color:#005CFE">profile details</h3> <br />
            <div class="col-xs-1 col-sm-1 col-md-1 column">
            <div class="profile_img">

            @{
                var imgPath = Directory.EnumerateFiles(Server.MapPath(@"~/Images/ProfileImages/"), "*.*", SearchOption.AllDirectories).Where(s => s.Contains(Model.RegNo));
                if(imgPath!=null && imgPath.Count()>0){

                            var img = new FileInfo(imgPath.First());
                            if(img!=null){
                                <img src="@Url.Content(String.Format("~/Images/ProfileImages/{0}",img.Name))" width="100" height="100" />
                            }

                 }
           }
            </div></div>
             <div class="col-xs-8 col-sm-8 col-md-8 column">
            <form class="form-horizontal profile_form timetable_div" role="form" >
            
                    <div class="form-group">
                    <label class="col-sm-6 control-label">Name</label>
                    <div class="col-sm-7 profile_details">
                        @Html.Label((string)ViewBag.Name)
                    </div>
                    </div> 

                     
                    <div class="form-group">
                    <label class="col-sm-6 control-label">NIC No</label>
                    <div class="col-sm-7 profile_details">
                        @Html.DisplayFor(model => model.NationalId, new { @class="form-control"})
                    </div>
                    </div>
       
                
                    <div class="form-group">
                    <label class="col-sm-6 control-label">Apla Registration No</label>
                    <div class="col-sm-7 profile_details">
                        @Html.DisplayFor(model => model.RegNo, new { @class="form-control"})
                    </div>
                    </div>

                 <div class="form-group">
                <label class="col-sm-6 control-label">Subjects</label>
                <div class="col-sm-7 profile_details">
                   @foreach (APLA.Models.Subject subject in Model.Subjects)
                        {
                            <label>@subject.Name</label>
                        } 
                </div>
                </div>

                   <div class="form-group">
            <label class="col-sm-4 control-label">Permanent Address</label>
            <div class="col-sm-7 profile_details">
                @Html.Label((string)ViewBag.permanentAddress)
            </div>
            </div> 


</form></div>
        </div>

          <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                        <input class="btn btn-primary" type="button" id="print" value="Print the Id">
                        <a class="btn btn-info" @Html.ActionLink("Back to List", "Index") 
                </div>
           </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#print").click(function () {
            $("#Content").printArea();
        });
    });
</script>

APLA/Views/Teacher/Index.cshtml
@model IEnumerable<APLA.Models.Teacher>
@{
    ViewBag.Title = "Teacher List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using GridMvc.Html
<div class="container">
    <div class="row">
<div class="container-fluid">
    <h2 style="text-align: center; color: #76BCF8">@ViewBag.Title</h2>
    <p>
        <a class="btn btn-success"  @Html.ActionLink("Create New", "Create") </a>
    </p>
</div>


@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.RegNo).Titled("Reg No").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.CommonName).Titled("First Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.FullName).Titled("Last Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Pho_M).Titled("Phone No").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Email).Titled("Email").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Enabled).Titled("Active").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Edit", "Edit", "Teacher", new { id = o.Id, page = ViewBag.Page }, new{@class ="btn btn-success"}).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Details", "Details", "Teacher", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-info" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Delete", "Delete", "Teacher", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-danger" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Change Password", "ChangePassword", "Teacher", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn" }).ToHtmlString());

          }).WithPaging(10)
</div>
    </div>

@*@model PagedList.IPagedList<APLA.Models.Teacher>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Teacher List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>

    select, textarea, input[type="text"], input[type="password"] {
        height:35px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="container-fluid">
            <h2 style="text-align:center;color:#76BCF8">@ViewBag.Title</h2>
    <p> 
        <a class="btn btn-success"  @Html.ActionLink("Create New", "Create") </a>
    </p>
            </div>


@using (Html.BeginForm("Index", "Teacher", FormMethod.Get, new { @class="form-inline"}))
{
    <div class="input-group">
       Find by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder="Search"})
         <span class="">
                    <input class="btn btn-default" type="submit" value="Search" />
                </span>
   </div>   
    
}
<table class="table table-bordered table-hover table-striped">
    <tr>
        <th style="text-align: center">
            @Html.ActionLink("Registration No", "Index", new { sortOrder = ViewBag.RegSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th style="text-align: center">
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th style="text-align: center">
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th style="text-align: center">
            Phone No
        </th>
        <th style="text-align: center">
            Email
        </th>
        <th style="text-align: center">
            Status
        </th>
        <th style="text-align: center">Action</th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
             @Html.DisplayFor(modelItem => item.RegNo)
        </td>
        <td>
             @Html.DisplayFor(modelItem => item.CommonName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pho_M)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Enabled)
        </td>
        <td>
            <a class="btn btn-default" @Html.ActionLink("Edit", "Edit", new { id=item.Id,page=Model.PageNumber })
            
               <a class="btn btn-info" @Html.ActionLink("Details", "Details", new { id=item.Id,page=Model.PageNumber }) 
         
               <a class="btn btn-danger" @Html.ActionLink("Delete", "Delete", new { id=item.Id,page=Model.PageNumber })

             <a class="btn btn-default" @Html.ActionLink("Change Password", "ChangePassword", new { id=item.Id,page=Model.PageNumber })
    </td>
        
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
new PagedListRenderOptions { MaximumPageNumbersToDisplay = 20 })
</div></div>*@